[settings]
lockfile = true
pin = true

[tools]
python = "3.14.4"
uv = "0.11.7"

[tasks.dev]
env = { PYTHONPATH = "{{config_root}}" }
run = "uv run yt-dlp"

[tasks.format]
description = "Check formatting"
run = "uv run ruff format --check ."

[tasks."format:fix"]
description = "Format"
run = "uv run ruff format ."

[tasks.lint]
description = "Lint"
run = "uv run ruff check ."

[tasks."lint:fix"]
description = "Auto-fix lint errors"
run = "uv run ruff check --fix ."
