[tools]
uv = "0.11.7"

[tasks.lint]
run = "uv run ruff check ."

[tasks."lint:fix"]
run = "uv run ruff check --fix ."

[tasks.format]
run = "uv run ruff format --check ."

[tasks."format:fix"]
run = "uv run ruff format ."
