[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "yt-dlp-kawadah-plugins"
version = "2026.04.22"
requires-python = ">=3.10"
classifiers = ["Private :: Do Not Upload"]

[dependency-groups]
dev = [
    "ruff",
    "yt-dlp>=2026.6.9",
]

[tool.setuptools.packages.find]
namespaces = true

[tool.ruff]
include = ["**/*.py", "**/pyproject.toml"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
