[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "yt-dlp-kawadah-plugins"
version = "2026.04.22"
description = "kawadah's yt-dlp plugins"
readme = "README.md"
requires-python = ">=3.10"
license = "Unlicense"
license-files = ["LICENSE"]
authors = [{ name = "kawadah" }]
classifiers = ["Private :: Do Not Upload"]

[project.urls]
Repository = "https://github.com/kawadah/yt-dlp-kawadah-plugins"

[dependency-groups]
dev = [
    "ruff>=0.16.3",
    "yt-dlp>=2026.7.4",
]

[tool.setuptools.packages.find]
namespaces = true

[tool.ruff]
include = ["**/*.py", "**/pyproject.toml"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
