name: Check Python

on:
  pull_request:
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
      - .github/workflows/check-python.yml

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install tools
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install_args: python uv
      - name: Check format
        run: mise run format:python
      - name: Lint
        run: mise run lint:python
